config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

match '/risks/preview/new/:project_id', :to => 'risks#preview', :as => 'preview_new_risk', :via => [:get, :post, :put, :patch]
match '/risks/preview/edit/:id', :to => 'risks#preview', :as => 'preview_edit_risk', :via => [:get, :post, :put, :patch]
post '/risks/:id/quoted', :to => 'risks#quoted', :id => /\d+/, :as => 'quoted_risk'
match '/risks/preview', :to => 'previews#text', :as => 'preview_risk', :via => [:get, :post, :put, :patch]

match '/risks/context_menu', :to => 'context_menus#risks', :as => 'risks_context_menu', :via => [:get, :post]
match 'auto_completes/risks' => 'auto_completes#risks', via: :get, as: 'auto_complete_risks'

resources :projects do
  resources :risks, :only => [:index, :new, :create]
end

resources :risks, :except => [:index, :new, :create] do
  post   'issues', :to => 'risk_issues#create_by_risk'
  delete 'issues/:issue_id', :to => 'risk_issues#destroy_by_risk'

  collection do
    post 'bulk_update'
  end
end

resources :issues, :except => [:index, :new, :create] do
  post   'risks', :to => 'risk_issues#create_by_issue'
  delete 'risks/:risk_id', :to => 'risk_issues#destroy_by_issue'

  collection do
    post 'bulk_update'
  end
end

match '/risks', :controller => 'risks', :action => 'destroy', :via => :delete

app/views/issues/_risk_relations.html.erb
<% if (User.current.allowed_to?(:view_risks, @project) && @issue.risks.any?) || User.current.allowed_to?(:manage_risk_relations, @project) %> 
  <hr />
  <div id="risk-relations">
    <%= render :partial => 'risks' %>
  </div>
<% end %>

app/views/issues/_risks.html.erb
<div class="contextual">
  <% if User.current.allowed_to?(:manage_risk_relations, @project) %>
    <%= toggle_link l(:button_add), 'new-risk-relation-form', {:focus => 'risk_id'} %>
  <% end %>
</div>

<p><strong><%=l(:label_related_risks)%></strong></p>
  <%= form_tag({}, :data => {:cm_url => risks_context_menu_path}) do %>
    <%= render_risks_relations(@issue) %>
  <% end %>

<% if User.current.allowed_to?(:manage_risk_relations, @project) %>
  <%= form_tag({:controller => 'risk_issues', :action => 'create_by_issue', :issue_id => @issue.id},
              :remote => true,
              :method => :post,
              :id => 'new-risk-relation-form',
              :style => 'display: none;') do |f| %>
    <%= l(:label_risk) %> #<%= text_field_tag 'risk_id', '', :size => 10 %>
    <%= submit_tag l(:button_add), :id => 'new_risk_on_issue' %>
    <%= link_to(l(:label_new_risk),
          new_project_risk_path(@issue.project),
          :remote => true,
          :method => 'get',
          :title => l(:label_new_risk),
          :tabindex => 200,
          :class => 'icon icon-add'
        ) if User.current.allowed_to?(:add_risks, @issue.project) %>
    <%= link_to_function l(:button_cancel), '$("#new-risk-relation-form").hide();'%>
  <% end %>
<% end %>

<%= javascript_tag "observeAutocompleteField('risk_id', '#{escape_javascript auto_complete_risks_path(:project_id => @project, :scope => 'all')}')" %>