config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

match '/risks/preview/new/:project_id', :to => 'risks#preview', :as => 'preview_new_risk', :via => [:get, :post, :put, :patch]
match '/risks/preview/edit/:id', :to => 'risks#preview', :as => 'preview_edit_risk', :via => [:get, :post, :put, :patch]
post '/risks/:id/quoted', :to => 'risks#quoted', :id => /\d+/, :as => 'quoted_risk'
match '/risks/preview', :to => 'previews#text', :as => 'preview_risk', :via => [:get, :post, :put, :patch]

match '/risks/context_menu', :to => 'context_menus#risks', :as => 'risks_context_menu', :via => [:get, :post]
match 'auto_completes/risks' => 'auto_completes#risks', via: :get, as: 'auto_complete_risks'

resources :projects do
  resources :risks, :only => [:index, :new, :create]
end

resources :risks, :except => [:index, :new, :create] do
  post   'issues', :to => 'risk_issues#create_by_risk'
  delete 'issues/:issue_id', :to => 'risk_issues#destroy_by_risk'

  collection do
    post 'bulk_update'
  end
end

resources :issues, :except => [:index, :new, :create] do
  post   'risks', :to => 'risk_issues#create_by_issue'
  delete 'risks/:risk_id', :to => 'risk_issues#destroy_by_issue'

  collection do
    post 'bulk_update'
  end
end

match '/risks', :controller => 'risks', :action => 'destroy', :via => :delete

app/models/risk_category.rb
class RiskCategory < Enumeration
  has_many :risks, :foreign_key => 'category_id'

  OptionName = :enumeration_risk_categories

  def option_name
    OptionName
  end

  def objects_count
    risks.count
  end

  def transfer_relations(to)
    risks.update_all(:category_id => to.id)
  end

  def self.default
    d = super
    d = first if d.nil?
    d
  end
end

app/views/context_menus/risks.html.erb
<ul>
  <%= call_hook(:view_risks_context_menu_start, {:risks => @risks, :can => @can, :back => @back }) %>

  <% if @safe_attributes.include?('assigned_to_id') && @assignables.present? -%>
    <li class="folder">
      <a href="#" class="submenu"><%= l(:field_assigned_to) %></a>
      <ul>
        <% if @assignables.include?(User.current) %>
          <li>
            <%= context_menu_link "<< #{l(:label_me)} >>", bulk_update_risks_path(:ids => @risk_ids, :risk => {'assigned_to_id' => User.current}, :back_url => @back),
                                  :method => :post,
                                  :disabled => !@can[:edit] %>
          </li>
        <% end %>
        <% @assignables.each do |u| -%>
          <li>
            <%= context_menu_link u.name, bulk_update_risks_path(:ids => @risk_ids, :risk => {'assigned_to_id' => u}, :back_url => @back),
                                  :method => :post,
                                  :selected => (@risk && u == @risk.assigned_to),
                                  :disabled => !@can[:edit] %>
          </li>
        <% end -%>
        <li>
          <%= context_menu_link l(:label_nobody), bulk_update_risks_path(:ids => @risk_ids, :risk => {'assigned_to_id' => 'none'}, :back_url => @back),
                                :method => :post,
                                :selected => (@risk && @risk.assigned_to.nil?),
                                :disabled => !@can[:edit] %>
        </li>
      </ul>
    </li>
  <% end %>

  <% if @safe_attributes.include?('category_id') && RiskCategory.active.any? -%>
    <li class="folder">
      <a href="#" class="submenu"><%= l(:field_category) %></a>
      <ul>
        <% RiskCategory.active.order('name ASC').each do |c| -%>
          <li>
            <%= context_menu_link c.name, bulk_update_risks_path(:ids => @risk_ids, :risk => {'category_id' => c.id}, :back_url => @back),
                                  :method => :post,
                                  :selected => (@risk && c == @risk.category),
                                  :disabled => !@can[:edit] %>
          </li>
        <% end -%>
        <li>
          <%= context_menu_link l(:label_none), bulk_update_risks_path(:ids => @risk_ids, :risk => {'category_id' => 'none'}, :back_url => @back),
                                :method => :post,
                                :selected => (@risk && @risk.category.nil?),
                                :disabled => !@can[:edit] %>
        </li>
      </ul>
    </li>
  <% end -%>

  <% if @safe_attributes.include?('impact') -%>
    <li class="folder">
      <a href="#" class="submenu"><%= l(:field_impact) %></a>
      <ul>
        <% (format_risk_levels(Risk::RISK_IMPACT) {|i| format_risk_impact(i)}).each do |i| -%>
          <li>
            <%= context_menu_link i[0], bulk_update_risks_path(:ids => @risk_ids, :risk => {'impact' => i[1]}, :back_url => @back),
                                  :method => :post,
                                  :selected => (@risk && i[1] == @risk.impact),
                                  :disabled => !@can[:edit] %>
          </li>
        <% end -%>
        <li>
          <%= context_menu_link l(:label_none), bulk_update_risks_path(:ids => @risk_ids, :risk => {'impact' => 'none'}, :back_url => @back),
                                :method => :post,
                                :selected => (@risk && @risk.impact.nil?),
                                :disabled => !@can[:edit] %>
        </li>
      </ul>
    </li>
  <% end -%>

  <% if @safe_attributes.include?('probability') -%>
    <li class="folder">
      <a href="#" class="submenu"><%= l(:field_probability) %></a>
      <ul>
        <% (format_risk_levels(Risk::RISK_PROBABILITY) {|p| format_risk_probability(p)}).each do |p| -%>
          <li>
            <%= context_menu_link p[0], bulk_update_risks_path(:ids => @risk_ids, :risk => {'probability' => p[1]}, :back_url => @back),
                                  :method => :post,
                                  :selected => (@risk && p[1] == @risk.probability),
                                  :disabled => !@can[:edit] %>
          </li>
        <% end -%>
        <li>
          <%= context_menu_link l(:label_none), bulk_update_risks_path(:ids => @risk_ids, :risk => {'probability' => 'none'}, :back_url => @back),
                                :method => :post,
                                :selected => (@risk && @risk.probability.nil?),
                                :disabled => !@can[:edit] %>
        </li>
      </ul>
    </li>
  <% end -%>

  <% if @safe_attributes.include?('strategy') -%>
    <li class="folder">
      <a href="#" class="submenu"><%= l(:field_strategy) %></a>
      <ul>
        <% Risk::RISK_STRATEGY.each do |s| -%>
          <li>
            <%= context_menu_link format_risk_strategy(s), bulk_update_risks_path(:ids => @risk_ids, :risk => {'strategy' => s}, :back_url => @back),
                                  :method => :post,
                                  :selected => (@risk && s == @risk.strategy),
                                  :disabled => !@can[:edit] %>
          </li>
        <% end -%>
        <li>
          <%= context_menu_link l(:label_none), bulk_update_risks_path(:ids => @risk_ids, :risk => {'strategy' => 'none'}, :back_url => @back),
                                :method => :post,
                                :selected => (@risk && @risk.strategy.nil?),
                                :disabled => !@can[:edit] %>
        </li>
      </ul>
    </li>
  <% end -%>

  <li>
    <%= context_menu_link l(:button_delete), risks_path(:ids => @risk_ids, :back_url => @back),
                            :method => :delete,
                            :data => {:confirm => l(:text_risks_destroy_confirmation)},
                            :class => 'icon icon-del',
                            :disabled => !@can[:delete] %>
  </li>

  <%= call_hook(:view_risks_context_menu_end, {:risks => @risks, :can => @can, :back => @back }) %>
</ul>