config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

match '/risks/preview/new/:project_id', :to => 'risks#preview', :as => 'preview_new_risk', :via => [:get, :post, :put, :patch]
match '/risks/preview/edit/:id', :to => 'risks#preview', :as => 'preview_edit_risk', :via => [:get, :post, :put, :patch]
post '/risks/:id/quoted', :to => 'risks#quoted', :id => /\d+/, :as => 'quoted_risk'
match '/risks/preview', :to => 'previews#text', :as => 'preview_risk', :via => [:get, :post, :put, :patch]

match '/risks/context_menu', :to => 'context_menus#risks', :as => 'risks_context_menu', :via => [:get, :post]
match 'auto_completes/risks' => 'auto_completes#risks', via: :get, as: 'auto_complete_risks'

resources :projects do
  resources :risks, :only => [:index, :new, :create]
end

resources :risks, :except => [:index, :new, :create] do
  post   'issues', :to => 'risk_issues#create_by_risk'
  delete 'issues/:issue_id', :to => 'risk_issues#destroy_by_risk'

  collection do
    post 'bulk_update'
  end
end

resources :issues, :except => [:index, :new, :create] do
  post   'risks', :to => 'risk_issues#create_by_issue'
  delete 'risks/:risk_id', :to => 'risk_issues#destroy_by_issue'

  collection do
    post 'bulk_update'
  end
end

match '/risks', :controller => 'risks', :action => 'destroy', :via => :delete

app/controllers/risks_controller.rb
class RisksController < ApplicationController
  default_search_scope :risks
  menu_item :risks

  before_action :find_risk, :only => [:show, :edit, :update, :quoted]
  before_action :find_risks, :only => [:bulk_update, :destroy]
  before_action :find_optional_project, :only => [:index, :new, :create]
  before_action :build_new_risk_from_params, :only => [:new, :create]

  rescue_from Query::StatementInvalid, :with => :query_statement_invalid

  helper :journals
  helper :projects
  helper :custom_fields
  include RisksHelper

  def index
    retrieve_query(RiskQuery)

    if @query.valid?
      respond_to do |format|
        format.html {
          @risk_count = @query.risk_count
          @risk_pages = Paginator.new @risk_count, per_page_option, params['page']
          @risks = @query.risks(:offset => @risk_pages.offset, :limit => @risk_pages.per_page)
          render :layout => !request.xhr?
        }
      end
    else
      respond_to do |format|
        format.html { render :layout => !request.xhr? }
      end
    end
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def new
    respond_to do |format|
      format.html { render :action => 'new', :layout => !request.xhr? }
      format.js { render :action => 'new', :layout => !request.xhr? }
    end
  end

  def create
    raise Unauthorized unless User.current.allowed_to?(:add_risks, @risk.project)

    unless @risk.save
      return respond_to do |format|
        format.html { render :action => 'new' }
        format.js { render :action => 'new' }
      end
    end

    respond_to do |format|
      format.html {
        flash[:notice] = l(:notice_risk_successful_create, :id => view_context.link_to("##{@risk.id}", risk_path(@risk), :title => @risk.subject))

        if params[:continue]
          redirect_to new_project_risk_path(@project, { :back_url => params[:back_url].presence })
        else
          redirect_back_or_default risk_path(@risk)
        end
      }
      format.js
    end
  end

  def show
    @journals = @risk.visible_journals_with_index

    if User.current.wants_comments_in_reverse_order?
      @journals.reverse!
    end

    respond_to do |format|
      format.html {
        render :template => 'risks/show'
      }
    end
  end

  def edit
    return unless update_risk_from_params

    respond_to do |format|
      format.html { }
    end
  end

  def update
    return unless update_risk_from_params

    saved = false
    begin
      saved = save_risk
    rescue ActiveRecord::StaleObjectError
      @conflict = true

      if params[:last_journal_id]
        @conflict_journals = @risk.journals_after(params[:last_journal_id]).to_a
        @conflict_journals.reject!(&:private_notes?) unless User.current.allowed_to?(:view_private_notes, @risk.project)
      end
    end

    if saved
      flash[:notice] = l(:notice_risk_successful_update) unless @risk.current_journal.new_record?

      respond_to do |format|
        format.html { redirect_back_or_default risk_path(@risk) }
        format.api  { render_api_ok }
      end
    else
      respond_to do |format|
        format.html { render :action => 'edit' }
        format.api  { render_validation_errors(@risk) }
      end
    end
  end

  def destroy
    raise Unauthorized unless @risks.all?(&:deletable?)

    @risks.each do |risk|
      begin
        risk.reload.destroy
      rescue ::ActiveRecord::RecordNotFound # raised by #reload if issue no longer exists
        # nothing to do, issue was already deleted (eg. by a parent)
      end
    end

    flash[:notice] = l(:notice_risk_successful_delete)

    respond_to do |format|
      format.html { redirect_back_or_default(@project ? project_risks_path(@project) : nil) }
      format.api  { render_api_ok }
    end
  end

  def preview
    @risk        = Risk.find_by_id(params[:id]) unless params[:id].blank?
    @description = params[:risk] && params[:risk][:description]

    if @risk
      raise Unauthorized unless @risk.editable? || @risk.notes_addable?

      if @description && @description.gsub(/(\r?\n|\n\r?)/, "\n") == @risk.description.to_s.gsub(/(\r?\n|\n\r?)/, "\n")
        @description = nil
      end

      @notes   = params[:journal] ? params[:journal][:notes] : nil
      @notes ||= params[:risk] ? params[:risk][:notes] : nil
    end

    render :layout => false
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def quoted
    raise Unauthorized unless @risk.notes_addable?

    user = @risk.author
    text = @risk.description

    # Replaces pre blocks with [...]
    text = text.to_s.strip.gsub(%r{<pre>(.*?)</pre>}m, '[...]')
    @content = "#{ll(Setting.default_language, :text_user_wrote, user)}\n> "
    @content << text.gsub(/(\r?\n|\r\n?)/, "\n> ") + "\n\n"

    render :template => 'journals/new'
  end

  def bulk_update
    @risks.sort!

    raise ::Unauthorized unless @risks.all?(&:attributes_editable?)

    attributes = parse_params_for_bulk_update(params[:risk])
    risks_unsaved = []
    risks_saved = []

    @risks.each do |risk_original|
      risk_original.reload

      risk = risk_original

      risk.init_journal(User.current, params[:notes])
      risk.safe_attributes = attributes

      if risk.save
        risks_saved << risk
      else
        risks_unsaved << risk_original
      end
    end

    if risks_unsaved.empty?
      flash[:notice] = l(:notice_risk_successful_update) unless risks_saved.empty?
    end

    redirect_back_or_default(@project ? project_risks_path(@project) : nil)
  end

  private

  def build_new_risk_from_params
    @risk = Risk.new
    @risk.project = @project
    @risk.author ||= User.current

    attrs = (params[:risk] || {}).deep_dup
    attrs.delete_if {|k,v| v.blank?}

    @risk.safe_attributes = attrs
  end

  def build_risk_params_for_update
    risk_attributes = (params[:risk] || {}).deep_dup
    risk_attributes.transform_values! { |value| value.present? ? value : nil }

    if risk_attributes && params[:conflict_resolution]
      case params[:conflict_resolution]
      when 'overwrite'
        risk_attributes.delete(:lock_version)
      when 'add_notes'
        risk_attributes = risk_attributes.slice(:notes, :private_notes)
      when 'cancel'
        return nil
      end
    end

    risk_attributes
  end

  # Used by #edit and #update to set some common instance variables
  # from the params
  def update_risk_from_params
    raise ::Unauthorized unless @risk.editable?

    risk_attributes = build_risk_params_for_update

    if risk_attributes.nil?
      redirect_to risk_path(@risk)
      return false
    end

    @risk.init_journal(User.current)
    @risk.safe_attributes = risk_attributes

    true
  end

  # Saves @risk from the parameters
  def save_risk
    Risk.transaction do
      call_hook(:controller_risks_edit_before_save, { :params => params, :risk => @risk, :journal => @risk.current_journal})

      raise ActiveRecord::Rollback unless @risk.save

      call_hook(:controller_risks_edit_after_save, { :params => params, :risk => @risk, :journal => @risk.current_journal})

      true
    end
  end
end

app/helpers/risks_helper.rb
module RisksHelper
  include IssuesHelper
  include QueriesHelper

  def find_risk
    risk_id = params[:risk_id] || params[:id]

    @risk = Risk.find(risk_id)
    raise Unauthorized unless @risk.visible?
    @project = @risk.project
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def find_risks
    @risks = Risk
      .where(:id => (params[:id] || params[:ids]))
      .preload(:project, :author, :assigned_to)
      .to_a

    raise ActiveRecord::RecordNotFound if @risks.empty?
    raise Unauthorized unless @risks.all?(&:visible?)

    @projects = @risks.collect(&:project).compact.uniq
    @project = @projects.first if @projects.size == 1
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def format_risk_status(status)
    l("label_risk_status_#{status}")
  end

  def format_risk_probability(probability)
    format_risk_level(Risk::RISK_PROBABILITY, probability) {|p| l("label_risk_probability_#{p}")}
  end

  def format_risk_impact(impact)
    format_risk_level(Risk::RISK_IMPACT, impact) {|i| l("label_risk_impact_#{i}")}
  end

  def format_risk_strategy(strategy)
    return unless Risk::RISK_STRATEGY.include?(strategy)
    l("label_risk_strategy_#{strategy}")
  end

  def format_risk_level(levels, level, &block)
    return if level.nil?

    increment = 100 / (levels.count - 1)

    if level % increment != 0
      return level.to_s + "%"
    end

    yield levels[level / increment]
  end

  def format_risk_levels(levels, value = nil, &block)
    index     = 0
    increment = 100 / (levels.count - 1)

    levels.collect do |level|
      value  = index * increment
      index += 1

      [yield(value), value]
    end
  end

  def render_risk_relations(risk)
    manage_relations = User.current.allowed_to?(:manage_risk_relations, risk.project)

    relations = risk.issues.visible.collect do |issue|
      delete_link = link_to(l(:label_relation_delete),
                            {:controller => 'risk_issues', :action => 'destroy_by_risk', :risk_id => @risk, :issue_id => issue},
                            :remote => true,
                            :method => :delete,
                            :data => {:confirm => l(:text_are_you_sure)},
                            :title => l(:label_relation_delete),
                            :class => 'icon-only icon-link-break')

      relation = ''.html_safe

      relation << content_tag('td', check_box_tag("ids[]", issue.id, false, :id => nil), :class => 'checkbox')
      relation << content_tag('td', link_to_issue(issue, :project => Setting.cross_project_issue_relations?).html_safe, :class => 'subject', :style => 'width: 50%')
      relation << content_tag('td', issue.status, :class => 'status')
      relation << content_tag('td', issue.start_date, :class => 'start_date')
      relation << content_tag('td', issue.due_date, :class => 'due_date')
      relation << content_tag('td', progress_bar(issue.done_ratio), :class=> 'done_ratio') unless issue.disabled_core_fields.include?('done_ratio')
      relation << content_tag('td', delete_link, :class => 'buttons') if manage_relations

      content_tag('tr', relation, :id => "relation-#{issue.id}", :class => "issue hascontextmenu #{issue.css_classes}")
    end

    content_tag('table', relations.join.html_safe, :class => 'list issues odd-even')
  end

  def render_risks_relations(issue)
    manage_relations = User.current.allowed_to?(:manage_risk_relations, issue.project)

    relations = issue.risks.collect do |risk|
      delete_link = link_to(l(:label_relation_delete),
                            {:controller => 'risk_issues', :action => 'destroy_by_issue', :risk_id => risk.id, :issue_id => issue.id},
                            :remote => true,
                            :method => :delete,
                            :data => {:confirm => l(:text_are_you_sure)},
                            :title => l(:label_relation_delete),
                            :class => 'icon-only icon-link-break')
      relation = ''.html_safe

      relation << content_tag('td', check_box_tag("ids[]", risk.id, false, :id => nil), :class => 'checkbox')
      relation << content_tag('td', format_risk_status(risk.status), :class => 'status')
      relation << content_tag('td', link_to(risk.project.name, project_path(risk.project)).html_safe, :class => 'project')
      relation << content_tag('td', link_to(risk.subject, risk_path(risk)).html_safe, :class => 'subject', :style => 'width: 50%')
      relation << content_tag('td', risk.category ? risk.category.name : "-", :class => 'category')
      relation << content_tag('td', risk.probability.present? ? format_risk_probability(risk.probability) : "-", :class => 'probability')
      relation << content_tag('td', risk.impact.present? ? format_risk_impact(risk.impact) : "-", :class => 'impact')
      relation << content_tag('td', risk.magnitude.present? ? risk.magnitude : "-", :class => 'magnitude')
      relation << content_tag('td', risk.strategy.present? ? format_risk_strategy(risk.strategy) : "-", :class => 'strategy')
      relation << content_tag('td', risk.assigned_to ? link_to_user(risk.assigned_to) : "-", :class => 'assigned-to')
      relation << content_tag('td', delete_link, :class => 'buttons') if manage_relations

      content_tag('tr', relation, :id => "risk-relation-#{risk.id}", :class => "risk hascontextmenu #{risk.css_classes}")
    end

    content_tag('table', relations.join.html_safe, :class => 'list risks odd-even')
  end

  def risk_details_to_strings(details, no_html=false, options={})
    # The plugin Redmine Checklists patch the method IssuesHelper::details_to_strings and suppose
    # that it's only used for issues. Thus, if the unpatched version exists, we'll use it instead.
    if respond_to?('details_to_strings_without_checklists')
      return details_to_strings_without_checklists(details, no_html, options)
    end

    details_to_strings(details, no_html, options)
  end

  def column_value_with_risks(column, item, value)
    if (item.is_a?(Risk)) 
      case column.name
      when :id, :subject
        link_to value, risk_path(item)
      when :probability
        format_risk_probability(value)
      when :impact
        format_risk_impact(value)
      when :status
        format_risk_status(value)
      when :strategy
        format_risk_strategy(value)
      when :treatments
        item.treatments? ? content_tag('div', textilizable(item, :treatments), :class => "wiki") : ''
      when :lessons
        item.lessons? ? content_tag('div', textilizable(item, :lessons), :class => "wiki") : ''
      else
        column_value_without_risks(column, item, value)
      end
    else
      column_value_without_risks(column, item, value)
    end
  end

  alias_method :column_value_without_risks, :column_value
  alias_method :column_value, :column_value_with_risks
end

app/views/risks/_action_menu.html.erb
<div class="contextual">
  <%= link_to l(:button_edit), edit_risk_path(@risk), :onclick => 'showAndScrollTo("update", "risk_notes"); return false;', :class => 'icon icon-edit', :accesskey => accesskey(:edit) if @risk.editable? %>
  <%= link_to l(:button_delete), risk_path(@risk), :data => {:confirm => l(:text_risks_destroy_confirmation)}, :method => :delete, :class => 'icon icon-del' if @risk.deletable? %>
</div>

app/views/risks/_attributes.html.erb
<%= labelled_fields_for :risk, @risk do |f| %>

  <% if @risk.safe_attribute? 'status' %>
    <p><%= f.select :status, Risk::RISK_STATUS.collect {|s| [format_risk_status(s), s]} %></p>
  <% end %>

  <% if @risk.safe_attribute? 'assigned_to_id' %>
    <p><%= f.select :assigned_to_id, principals_options_for_select(@risk.assignable_users, @risk.assigned_to), :include_blank => true %></p>
  <% end %>

  <% if @risk.safe_attribute?('category_id') && RiskCategory.active.any? %>
    <p><%= f.select :category_id, RiskCategory.active.order('name ASC').collect {|c| [c.name, c.id]}, :include_blank => true %></p>
  <% end %>

  <% if @risk.safe_attribute?('probability') %>
    <p><%= f.select :probability, format_risk_levels(Risk::RISK_PROBABILITY, @risk.probability) {|p| format_risk_probability(p)}, :include_blank => true %></p>
  <% end %>

  <% if @risk.safe_attribute?('impact') %>
    <p><%= f.select :impact, format_risk_levels(Risk::RISK_IMPACT, @risk.impact) {|i| format_risk_impact(i)}, :include_blank => true %></p>
  <% end %>

  <% if @risk.safe_attribute?('strategy') && ! @risk.new_record? %>
    <p><%= f.select :strategy, Risk::RISK_STRATEGY.collect {|p| [format_risk_strategy(p), p]}, :include_blank => true %></p>
  <% end %>
<% end %>

app/views/risks/_form.html.erb
<%= labelled_fields_for :risk, @risk do |f| %>
  <% if @risk.safe_attribute? 'subject' %>
    <p><%= f.text_field :subject, :size => 80, :maxlength => 255, :required => true %></p>
  <% end %>

  <% if @risk.safe_attribute? 'description' %>
    <p>
      <%= f.label_for_field :description %>
      <%= link_to_function content_tag(:span, l(:button_edit), :class => 'icon icon-edit'), '$(this).hide(); $("#risk_description_and_toolbar").show()' unless @risk.new_record? %>
      <%= content_tag 'span', :id => "risk_description_and_toolbar", :style => (@risk.new_record? ? nil : 'display:none') do %>
        <%= f.text_area :description,
                        :cols => 60,
                        :rows => [[10, @risk.description.to_s.length / 50].max, 20].min,
                        :accesskey => accesskey(:edit),
                        :class => 'wiki-edit',
                        :no_label => true %>
      <% end %>
    </p>

    <%= wikitoolbar_for 'risk_description', preview_risk_path(:project_id => @risk.project) %>
  <% end %>

  <div id="attributes" class="attributes">
    <%= render :partial => 'risks/attributes' %>
  </div>

  <% if @risk.safe_attribute?('treatments') && ! @risk.new_record? %>
    <p>
      <%= f.label_for_field :treatments %>
      <%= link_to_function content_tag(:span, l(:button_edit), :class => 'icon icon-edit'), '$(this).hide(); $("#risk_treatments_and_toolbar").show()' unless @risk.new_record? %>
      <%= content_tag 'span', :id => "risk_treatments_and_toolbar", :style => (@risk.new_record? ? nil : 'display:none') do %>
        <%= f.text_area :treatments,
                        :cols => 60,
                        :rows => [[10, @risk.treatments.to_s.length / 50].max, 20].min,
                        :accesskey => accesskey(:edit),
                        :class => 'wiki-edit',
                        :no_label => true %>
      <% end %>
    </p>
    <%= wikitoolbar_for 'risk_treatments' %>
  <% end %>

  <% if @risk.safe_attribute?('lessons') && ! @risk.new_record? %>
    <p>
      <%= f.label_for_field :lessons %>
      <%= link_to_function content_tag(:span, l(:button_edit), :class => 'icon icon-edit'), '$(this).hide(); $("#risk_lessons_and_toolbar").show()' unless @risk.new_record? %>
      <%= content_tag 'span', :id => "risk_lessons_and_toolbar", :style => (@risk.new_record? ? nil : 'display:none') do %>
        <%= f.text_area :lessons,
                        :cols => 60,
                        :rows => [[10, @risk.lessons.to_s.length / 50].max, 20].min,
                        :accesskey => accesskey(:edit),
                        :class => 'wiki-edit',
                        :no_label => true %>
      <% end %>
    </p>
    <%= wikitoolbar_for 'risk_lessons' %>
  <% end %>

  <%= call_hook(:view_risks_form_details_bottom, { :risk => @risk, :form => f }) %>
<% end %>

app/views/risks/_list.html.erb
<% query_options = nil unless defined?(query_options) %>
<% query_options ||= {} %>

<%= form_tag({}, :data => {:cm_url => risks_context_menu_path}) do -%>
  <%= hidden_field_tag 'back_url', url_for(:params => request.query_parameters), :id => nil %>

  <div class="autoscroll">
    <table class="list risks odd-even <%= query.css_classes %>">
      <thead>
      <tr>
        <th class="checkbox hide-when-print">
          <%= check_box_tag 'check_all', '', false, :class => 'toggle-selection',
                            :title => "#{l(:button_check_all)}/#{l(:button_uncheck_all)}" %>
        </th>
        <% query.inline_columns.each do |column| %>
          <%= column_header(query, column, query_options) %>
        <% end %>
      </tr>
      </thead>
      <tbody>
      <% grouped_query_results(risks, query) do |risk, group_name, group_count, group_totals| -%>
        <% if group_name %>
          <% reset_cycle %>
          <tr class="group open">
            <td colspan="<%= query.inline_columns.size + 1 %>">
              <span class="expander" onclick="toggleRowGroup(this);">&nbsp;</span>
              <span class="name"><%= group_name %></span> <span class="count"><%= group_count %></span> <span class="totals"><%= group_totals %></span>
              <%= link_to_function("#{l(:button_collapse_all)}/#{l(:button_expand_all)}",
                                   "toggleAllRowGroups(this)", :class => 'toggle-all') %>
            </td>
          </tr>
        <% end %>
        <tr id="risk-<%= risk.id %>" class="hascontextmenu <%= cycle('odd', 'even') %> <%= risk.css_classes %>">
          <td class="checkbox hide-when-print"><%= check_box_tag("ids[]", risk.id, false, :id => nil) %></td>
          <% query.inline_columns.each do |column| %>
            <%= content_tag('td', column_content(column, risk), :class => column.css_classes) %>
          <% end %>
        </tr>
        <% query.block_columns.each do |column| -%>
          <% if (text = column_content(column, risk)) && text.present? -%>
            <tr class="<%= current_cycle %>">
              <td colspan="<%= query.inline_columns.size + 1 %>" class="<%= column.css_classes %>">
                <% if query.block_columns.count > 1 %>
                  <span><%= column.caption %></span>
                <% end %>
                <%= text %>
              </td>
            </tr>
          <% end -%>
        <% end -%>
      <% end -%>
      </tbody>
    </table>
  </div>
<% end -%>

app/views/risks/_new_modal.html.erb
<h3 class="title"><%=l(:label_new_risk)%></h3>
<%= labelled_form_for @risk, :url => project_risks_path(@project), :remote => true do |f| %>
<%= error_messages_for 'risk' %>
<div class="box tabular">
  <%= render :partial => 'form', :locals => { :f => f } %>
</div>
<p class="buttons">
  <%= submit_tag l(:button_create), :name => nil %>
  <%= link_to_function l(:button_cancel), "hideModal(this);" %>
</p>
<% end %>

app/views/risks/_relations.html.erb
<% manage_allowed = User.current.allowed_to?(:manage_risk_relations, @project) %>

<div class="contextual">
  <% if manage_allowed %>
    <%= toggle_link l(:button_add), 'new-relation-form', {:focus => 'issue_id'} %>
  <% end %>
</div>

<p><strong><%=l(:label_related_issues)%></strong></p>

<%= form_tag({}, :data => {:cm_url => issues_context_menu_path}) do %>
  <%= render_risk_relations(@risk) %>
<% end %>

<% if manage_allowed %>
  <%= form_tag({:controller => 'risk_issues', :action => 'create_by_risk', :risk_id => @risk},
               :remote => true,
               :method => :post,
               :id => 'new-relation-form',
               :style => 'display: none;') do |f| %>
    <%= l(:label_issue) %> #<%= text_field_tag 'issue_id', '', :size => 10 %>
    <%= submit_tag l(:button_add) %>
    <%= toggle_link l(:button_cancel), 'new-relation-form'%>
  <% end %>
<% end %>

<%= javascript_tag "observeAutocompleteField('issue_id', '#{escape_javascript auto_complete_issues_path(:project_id => @project, :scope => 'all')}')" %>

app/views/risks/edit.html.erb
<h2><%= l(:label_risk) %> #<%= @risk.id %></h2>

<%= render :partial => 'edit' %>

<% content_for :header_tags do %>
    <%= robot_exclusion_tag %>
<% end %>

app/views/risks/new.html.erb
<%= title l(:label_new_risk) %>

<%= call_hook(:view_risk_new_top, {:risk => @risk}) %>

<%= labelled_form_for @risk, :url => project_risks_path(@project), :html => {:id => 'risk-form'} do |f| %>
  <%= error_messages_for 'risk' %>
  <div class="box tabular">
    <div id="all_attributes">
      <%= render :partial => 'form', :locals => {:f => f} %>
    </div>
  </div>

  <%= submit_tag l(:button_create) %>
  <%= submit_tag l(:button_create_and_continue), :name => 'continue' %>
  <% if Redmine::VERSION.to_s < '4.0' %>
    <%= preview_link preview_new_risk_path(:project_id => @risk.project), 'risk-form' %>
  <% end %>
<% end %>

<% if Redmine::VERSION.to_s < '4.0' %>
  <div id="preview" class="wiki"></div>
<% end %>

<% content_for :header_tags do %>
  <%= robot_exclusion_tag %>
<% end %>

app/views/risks/show.html.erb
<%= render :partial => 'action_menu' %>

<h2><%= l(:label_risk) %> #<%= @risk.id %></h2>

<div class="<%= @risk.css_classes %> issue details">
  <div class="subject">
    <h3><%= @risk.subject %></h3>
  </div>

  <p class="author">
    <%= authoring @risk.created_on, @risk.author %>.
    <% if @risk.created_on != @risk.updated_on %>
      <%= l(:label_updated_time, time_tag(@risk.updated_on)).html_safe %>.
    <% end %>
  </p>

  <div class="attributes">
    <%= issue_fields_rows do |rows|
      rows.left l(:field_status), format_risk_status(@risk.status), :class => 'status'

      rows.left l(:field_assigned_to), (@risk.assigned_to ? link_to_user(@risk.assigned_to) : "-"), :class => 'assigned-to'

      rows.left l(:field_category), (@risk.category ? @risk.category.name : "-"), :class => 'category'

      rows.left l(:field_probability), (@risk.probability.present? ? format_risk_probability(@risk.probability) : "-"), :class => 'probability'

      rows.left l(:field_impact), (@risk.impact.present? ? format_risk_impact(@risk.impact) : "-"), :class => 'impact'

      rows.left l(:field_strategy), (@risk.strategy.present? ? format_risk_strategy(@risk.strategy) : "-"), :class => 'strategy'
    end %>
  </div>

  <% if @risk.description? -%>
    <hr />

    <div class="description">
      <div class="contextual">
        <%= link_to l(:button_quote), quoted_risk_path(@risk), :remote => true, :method => 'post', :class => 'icon icon-comment' if @risk.notes_addable? %>
      </div>

      <p><strong><%=l(:field_description)%></strong></p>
      <div class="wiki">
        <%= textilizable @risk, :description %>
      </div>
    </div>
  <% end -%>

  <% if @risk.treatments? %>
    <hr />

    <div class="treatments">
      <p><strong><%=l(:field_treatments)%></strong></p>
      <div class="wiki">
        <%= textilizable @risk, :treatments %>
      </div>
    </div>
  <% end %>

  <% if @risk.lessons? -%>
    <hr />

    <div class="lessons">
      <p><strong><%=l(:field_lessons)%></strong></p>
      <div class="wiki">
        <%= textilizable @risk, :lessons %>
      </div>
    </div>
  <% end -%>

  <hr />

  <div id="relations">
    <%= render :partial => 'relations' %>
  </div>
</div>

<% if @journals.present? %>
  <div id="history">
    <h3><%=l(:label_history)%></h3>
    <%= render :partial => 'history', :locals => { :risk => @risk, :journals => @journals } %>
  </div>
<% end %>

<div style="clear: both;"></div>

<%= render :partial => 'action_menu' %>

<% if @risk.editable? %>
  <div id="update" style="display:none;">
    <h3><%= l(:button_edit) %></h3>
    <%= render :partial => 'edit' %>
  </div>
<% end %>

<% html_title l(:label_risk) + " ##{@risk.id}: #{@risk.subject}" %>

<%= context_menu %>